// src/seeders/foodSeeder.js
// Seeds 130+ authentic Pakistani foods with full disease-safety flags
// Research sources: Food Tribune PK, Tribune.com.pk, Wikipedia Pakistani Cuisine,
//                   BazaarApp.com, TheLandOfPurePeople.com, Graana.com
// Run: npm run seed

require('dotenv').config();
const mongoose = require('mongoose');
const FoodItem = require('../models/FoodItem');
const connectDB = require('../config/database');

const pakistaniFoods = [
  // ══════════════════════════════════════════════════════
  // BREAKFAST ITEMS
  // ══════════════════════════════════════════════════════
  {
    name: 'Aloo Paratha',
    calories: 320, protein: 7, carbs: 48, fat: 12, fiber: 3,
    price: 50, servingSize: '2 parathas (200g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['gluten'],
    description: 'Classic Pakistani stuffed bread with spiced potato filling',
  },
  {
    name: 'Halwa Puri',
    calories: 450, protein: 8, carbs: 60, fat: 20, fiber: 2,
    price: 80, servingSize: '1 plate',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['gluten'],
    description: 'Traditional Pakistani Sunday breakfast — fried bread with semolina dessert',
  },
  {
    name: 'Anda Paratha',
    calories: 370, protein: 14, carbs: 45, fat: 16, fiber: 2,
    price: 60, servingSize: '1 paratha with egg (220g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['gluten', 'eggs'],
    description: 'Egg-stuffed whole wheat paratha',
  },
  {
    name: 'Doodh Pati Chai',
    calories: 120, protein: 4, carbs: 14, fat: 5, fiber: 0,
    price: 20, servingSize: '1 cup (240ml)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'beverage', mealType: ['breakfast', 'snack'],
    allergens: ['dairy'],
    description: 'Strong Pakistani milk tea',
  },
  {
    name: 'Namkeen Lassi',
    calories: 150, protein: 8, carbs: 12, fat: 7, fiber: 0,
    price: 40, servingSize: '1 glass (300ml)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'beverage', mealType: ['breakfast', 'lunch'],
    allergens: ['dairy'],
    description: 'Salty yogurt-based drink, popular in Faisalabad and Punjab',
  },
  {
    name: 'Meethi Lassi',
    calories: 220, protein: 8, carbs: 30, fat: 7, fiber: 0,
    price: 50, servingSize: '1 glass (300ml)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'beverage', mealType: ['breakfast'],
    allergens: ['dairy'],
    description: 'Sweet yogurt drink, Punjabi staple',
  },
  {
    name: 'Anday ka Nashta',
    calories: 250, protein: 18, carbs: 5, fat: 17, fiber: 1,
    price: 55, servingSize: '2 eggs with vegetables (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['eggs'],
    description: 'Pakistani spiced scrambled eggs (bhurji) with tomatoes and onions',
  },
  {
    name: 'Khichdi',
    calories: 280, protein: 9, carbs: 52, fat: 5, fiber: 4,
    price: 45, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'breakfast', mealType: ['breakfast', 'dinner'],
    allergens: [],
    description: 'Comforting rice and lentil porridge — gentle on stomach, kidney-friendly',
  },
  {
    name: 'Boiled Egg White Breakfast',
    calories: 100, protein: 20, carbs: 2, fat: 1, fiber: 0,
    price: 35, servingSize: '4 egg whites (160g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['eggs'],
    description: 'Boiled egg whites — high protein, low fat, cardiac and diabetic safe',
  },
  {
    name: 'Oats Porridge (Dalia)',
    calories: 210, protein: 7, carbs: 38, fat: 4, fiber: 5,
    price: 40, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['gluten'],
    description: 'Slow-cooked oat porridge — excellent for blood sugar and heart health',
  },
  {
    name: 'Sattu Sharbat',
    calories: 180, protein: 6, carbs: 35, fat: 2, fiber: 3,
    price: 30, servingSize: '1 glass (300ml)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'beverage', mealType: ['breakfast', 'snack'],
    allergens: ['gluten'],
    description: 'Roasted gram flour drink — traditional Punjabi energy drink',
  },
  {
    name: 'Nihari with Naan',
    calories: 520, protein: 28, carbs: 52, fat: 22, fiber: 2,
    price: 180, servingSize: '1 bowl with 1 naan (400g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['gluten'],
    description: 'Slow-cooked beef stew — traditional Pakistani breakfast, iron-rich',
  },
  {
    name: 'Paye (Trotters Soup)',
    calories: 280, protein: 22, carbs: 4, fat: 18, fiber: 0,
    price: 120, servingSize: '1 bowl (300ml)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: [],
    description: 'Slow-cooked goat trotters soup — warming winter breakfast, collagen-rich',
  },

  // ══════════════════════════════════════════════════════
  // BREAD
  // ══════════════════════════════════════════════════════
  {
    name: 'Tandoori Roti',
    calories: 120, protein: 4, carbs: 24, fat: 1, fiber: 2,
    price: 15, servingSize: '1 roti (90g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'bread', mealType: ['lunch', 'dinner'],
    allergens: ['gluten'],
    description: 'Whole wheat flatbread baked in tandoor oven',
  },
  {
    name: 'Chapati (Phulka)',
    calories: 100, protein: 3, carbs: 20, fat: 1, fiber: 2,
    price: 10, servingSize: '1 chapati (70g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'bread', mealType: ['lunch', 'dinner'],
    allergens: ['gluten'],
    description: 'Thin whole wheat flatbread cooked on tawa — Pakistani daily staple',
  },
  {
    name: 'Naan',
    calories: 260, protein: 8, carbs: 48, fat: 4, fiber: 2,
    price: 25, servingSize: '1 naan (150g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'bread', mealType: ['lunch', 'dinner'],
    allergens: ['gluten', 'dairy'],
    description: 'Leavened tandoor-baked bread',
  },
  {
    name: 'Paratha (Plain)',
    calories: 250, protein: 5, carbs: 35, fat: 10, fiber: 2,
    price: 30, servingSize: '1 paratha (120g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'bread', mealType: ['breakfast', 'lunch'],
    allergens: ['gluten'],
    description: 'Layered whole wheat flatbread cooked with ghee or oil',
  },
  {
    name: 'Missi Roti',
    calories: 130, protein: 5, carbs: 22, fat: 3, fiber: 4,
    price: 15, servingSize: '1 roti (80g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'bread', mealType: ['breakfast', 'lunch', 'dinner'],
    allergens: ['gluten'],
    description: 'Chickpea flour and wheat flatbread — high protein, high fiber, diabetic-friendly',
  },
  {
    name: 'Bajra Roti',
    calories: 110, protein: 3, carbs: 20, fat: 2, fiber: 3,
    price: 12, servingSize: '1 roti (75g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: true,
    category: 'bread', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Pearl millet flatbread — gluten-free, high iron, winter staple in rural Punjab',
  },

  // ══════════════════════════════════════════════════════
  // LENTILS (DAAL)
  // ══════════════════════════════════════════════════════
  {
    name: 'Dal Masoor',
    calories: 230, protein: 15, carbs: 38, fat: 3, fiber: 8,
    price: 60, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'lentils', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Red lentil curry — most common Pakistani household dal, iron-rich',
  },
  {
    name: 'Dal Mash',
    calories: 210, protein: 14, carbs: 32, fat: 4, fiber: 7,
    price: 70, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'lentils', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'White lentil curry, Punjabi specialty',
  },
  {
    name: 'Dal Chana',
    calories: 250, protein: 13, carbs: 42, fat: 4, fiber: 9,
    price: 65, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'lentils', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Split chickpea lentil curry',
  },
  {
    name: 'Chana Masala',
    calories: 270, protein: 14, carbs: 40, fat: 6, fiber: 10,
    price: 80, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'lentils', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Spiced chickpea curry — protein-rich Pakistani staple',
  },
  {
    name: 'Moong Dal (Yellow)',
    calories: 190, protein: 12, carbs: 30, fat: 2, fiber: 6,
    price: 55, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'lentils', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Yellow split mung beans — lightest dal, kidney-friendly, easy to digest',
  },
  {
    name: 'Kala Chana',
    calories: 260, protein: 15, carbs: 42, fat: 4, fiber: 12,
    price: 70, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'lentils', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Black chickpeas curry — very high fiber and iron, common in Pakistani households',
  },
  {
    name: 'Dal Makhani',
    calories: 290, protein: 14, carbs: 38, fat: 9, fiber: 8,
    price: 90, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'lentils', mealType: ['dinner'],
    allergens: ['dairy'],
    description: 'Slow-cooked black lentils with cream and butter — rich, indulgent',
  },

  // ══════════════════════════════════════════════════════
  // MEAT DISHES
  // ══════════════════════════════════════════════════════
  {
    name: 'Chicken Karahi',
    calories: 380, protein: 32, carbs: 8, fat: 24, fiber: 2,
    price: 200, servingSize: '1 serving (300g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Classic Pakistani wok-cooked spicy chicken — Faisalabad style',
  },
  {
    name: 'Chicken Roast (Desi)',
    calories: 340, protein: 35, carbs: 5, fat: 20, fiber: 1,
    price: 180, servingSize: '2 pieces (250g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Spiced whole roasted chicken pieces',
  },
  {
    name: 'Beef Qeema',
    calories: 360, protein: 28, carbs: 6, fat: 25, fiber: 2,
    price: 160, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Minced beef curry with peas — Pakistani household staple, iron-rich',
  },
  {
    name: 'Mutton Karahi',
    calories: 420, protein: 30, carbs: 6, fat: 30, fiber: 2,
    price: 280, servingSize: '1 serving (300g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Rich mutton karahi — special occasion dish in Faisalabad',
  },
  {
    name: 'Chicken Tikka (Grilled)',
    calories: 290, protein: 38, carbs: 4, fat: 13, fiber: 1,
    price: 220, servingSize: '4 pieces (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner', 'snack'],
    allergens: ['dairy'],
    description: 'Yogurt-marinated grilled chicken — healthier option',
  },
  {
    name: 'Steamed Fish (Rohu)',
    calories: 180, protein: 30, carbs: 0, fat: 5, fiber: 0,
    price: 150, servingSize: '1 fillet (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Steamed freshwater fish — excellent for cardiac, kidney, and thyroid patients',
  },
  {
    name: 'Chicken Soup (Yakhni)',
    calories: 140, protein: 20, carbs: 5, fat: 4, fiber: 1,
    price: 80, servingSize: '1 bowl (300ml)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Clear bone broth chicken soup — gentle, healing, multi-condition safe',
  },
  {
    name: 'Grilled Chicken Breast',
    calories: 220, protein: 40, carbs: 2, fat: 5, fiber: 0,
    price: 200, servingSize: '1 breast (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Plain grilled chicken breast — lean protein, heart and diabetes safe',
  },
  {
    name: 'Chapli Kebab',
    calories: 310, protein: 22, carbs: 10, fat: 20, fiber: 2,
    price: 120, servingSize: '2 kebabs (180g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner', 'snack'],
    allergens: ['eggs'],
    description: 'Flat spiced minced beef kebab — Peshawar specialty, popular across Pakistan',
  },
  {
    name: 'Seekh Kebab',
    calories: 280, protein: 24, carbs: 6, fat: 17, fiber: 1,
    price: 100, servingSize: '3 seekhs (180g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner', 'snack'],
    allergens: [],
    description: 'Ground meat on skewers, grilled over charcoal — street food staple',
  },
  {
    name: 'Beef Nihari',
    calories: 400, protein: 26, carbs: 12, fat: 28, fiber: 2,
    price: 160, servingSize: '1 bowl (300g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['breakfast', 'lunch'],
    allergens: ['gluten'],
    description: 'Slow-cooked beef shin stew — traditional morning dish, iron-rich',
  },
  {
    name: 'Aloo Gosht',
    calories: 350, protein: 22, carbs: 25, fat: 18, fiber: 3,
    price: 150, servingSize: '1 bowl (300g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Potato and mutton curry — beloved Pakistani comfort food',
  },
  {
    name: 'Karahi Gosht',
    calories: 440, protein: 32, carbs: 8, fat: 32, fiber: 2,
    price: 300, servingSize: '1 serving (300g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Wok-cooked mutton curry with tomatoes — celebration food in Pakistan',
  },
  {
    name: 'Shami Kebab',
    calories: 200, protein: 15, carbs: 12, fat: 10, fiber: 3,
    price: 80, servingSize: '3 kababs (150g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'meat', mealType: ['snack', 'lunch'],
    allergens: ['eggs'],
    description: 'Ground beef and lentil pan-fried patties — household favorite',
  },
  {
    name: 'Chicken Korma',
    calories: 380, protein: 28, carbs: 12, fat: 24, fiber: 2,
    price: 220, servingSize: '1 bowl (280g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['dinner'],
    allergens: ['dairy', 'nuts'],
    description: 'Creamy yogurt-based chicken curry — served at weddings and dawaat',
  },
  {
    name: 'Liver (Kaleji) Masala',
    calories: 230, protein: 26, carbs: 6, fat: 11, fiber: 1,
    price: 120, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['breakfast', 'lunch'],
    allergens: [],
    description: 'Spiced beef or mutton liver — extremely iron-rich, best for anemia',
  },
  {
    name: 'Fish Karahi (Machli)',
    calories: 280, protein: 32, carbs: 6, fat: 14, fiber: 1,
    price: 200, servingSize: '1 serving (280g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Pakistani spiced fish wok curry — popular in Punjab and Sindh',
  },

  // ══════════════════════════════════════════════════════
  // VEGETABLES & SABZI
  // ══════════════════════════════════════════════════════
  {
    name: 'Saag (Sarson ka)',
    calories: 180, protein: 8, carbs: 20, fat: 8, fiber: 6,
    price: 70, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: true,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Mustard greens with butter — iconic Punjabi winter dish. Not recommended for thyroid patients',
  },
  {
    name: 'Bhindi Masala',
    calories: 150, protein: 4, carbs: 18, fat: 7, fiber: 5,
    price: 60, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Spiced okra stir-fry — diabetic-friendly, kidney-safe low potassium vegetable',
  },
  {
    name: 'Karela (Bitter Gourd)',
    calories: 90, protein: 3, carbs: 12, fat: 3, fiber: 4,
    price: 50, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Bitter gourd sabzi — excellent blood sugar control, known as "plant insulin"',
  },
  {
    name: 'Tinda Masala',
    calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 3,
    price: 55, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Indian round gourd — low potassium, kidney-friendly, thyroid safe',
  },
  {
    name: 'Palak Sabzi (Spinach)',
    calories: 130, protein: 7, carbs: 14, fat: 6, fiber: 4,
    price: 55, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: true,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Cooked spinach sabzi — iron-rich, excellent for anemia. Avoid in thyroid and kidney disease',
  },
  {
    name: 'Lauki (Bottle Gourd) Sabzi',
    calories: 80, protein: 2, carbs: 12, fat: 3, fiber: 3,
    price: 45, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Bottle gourd curry — extremely low potassium and phosphorus, ideal for kidney patients',
  },
  {
    name: 'Turai (Ridge Gourd) Sabzi',
    calories: 75, protein: 2, carbs: 10, fat: 3, fiber: 3,
    price: 45, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Ridge gourd curry — very low mineral content, safe for kidney disease',
  },
  {
    name: 'Aloo Matar',
    calories: 180, protein: 5, carbs: 30, fat: 5, fiber: 4,
    price: 65, servingSize: '1 bowl (250g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Potato and peas curry — common Pakistani sabzi',
  },
  {
    name: 'Baingan Bharta',
    calories: 140, protein: 4, carbs: 18, fat: 6, fiber: 5,
    price: 60, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Roasted and mashed eggplant — smoky, flavorful Pakistani sabzi',
  },
  {
    name: 'Gobi Masala (Cauliflower)',
    calories: 140, protein: 5, carbs: 18, fat: 6, fiber: 4,
    price: 60, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Spiced cauliflower stir-fry — winter vegetable. Goitrogen: avoid in thyroid',
  },
  {
    name: 'Aloo Gobi',
    calories: 160, protein: 4, carbs: 26, fat: 5, fiber: 4,
    price: 65, servingSize: '1 bowl (230g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Potato and cauliflower curry — popular Pakistani sabzi. Not ideal for thyroid',
  },
  {
    name: 'Palak Paneer',
    calories: 280, protein: 14, carbs: 18, fat: 17, fiber: 4,
    price: 120, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: true,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Spinach and cottage cheese curry. High iron for anemia; avoid in thyroid/kidney',
  },
  {
    name: 'Kadu (Pumpkin) Gosht',
    calories: 240, protein: 18, carbs: 20, fat: 10, fiber: 3,
    price: 120, servingSize: '1 bowl (280g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Pumpkin and meat curry — popular in Sindh and KPK, low calorie vegetable',
  },
  {
    name: 'Methi (Fenugreek) Sabzi',
    calories: 100, protein: 5, carbs: 14, fat: 4, fiber: 5,
    price: 50, servingSize: '1 bowl (180g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Fenugreek leaves sabzi — blood sugar lowering, iron-rich winter green',
  },
  {
    name: 'Arvi (Taro Root) Masala',
    calories: 150, protein: 3, carbs: 28, fat: 4, fiber: 4,
    price: 55, servingSize: '1 bowl (200g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Taro root curry — starchy winter vegetable, common in Pakistani households',
  },
  {
    name: 'Shaljam (Turnip) Gosht',
    calories: 200, protein: 15, carbs: 16, fat: 8, fiber: 4,
    price: 100, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Turnip and meat curry — winter staple, budget-friendly. Goitrogen: avoid in thyroid',
  },
  {
    name: 'Band Gobi (Cabbage) Sabzi',
    calories: 100, protein: 3, carbs: 14, fat: 4, fiber: 4,
    price: 40, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: false, is_constipation_safe: true, is_anemia_safe: false,
    category: 'vegetable', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Cabbage stir-fry — budget winter vegetable. Goitrogen: avoid in thyroid',
  },
  {
    name: 'Gajar Halwa',
    calories: 320, protein: 5, carbs: 50, fat: 12, fiber: 3,
    price: 80, servingSize: '1 bowl (150g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dessert', mealType: ['snack', 'dinner'],
    allergens: ['dairy', 'nuts'],
    description: 'Carrot pudding with milk and ghee — beloved Pakistani winter dessert',
  },
  {
    name: 'Aloo Keema',
    calories: 320, protein: 22, carbs: 22, fat: 16, fiber: 3,
    price: 140, servingSize: '1 bowl (250g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'meat', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Minced beef with potatoes — very common Pakistani meal',
  },

  // ══════════════════════════════════════════════════════
  // RICE DISHES
  // ══════════════════════════════════════════════════════
  {
    name: 'Plain Boiled Rice',
    calories: 200, protein: 4, carbs: 44, fat: 0.5, fiber: 1,
    price: 30, servingSize: '1 cup cooked (180g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'rice', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Simple steamed white rice — low phosphorus, kidney-safe in moderation',
  },
  {
    name: 'Chicken Biryani',
    calories: 480, protein: 25, carbs: 65, fat: 14, fiber: 2,
    price: 180, servingSize: '1 plate (350g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'rice', mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Aromatic Pakistani chicken biryani — celebration food across Pakistan',
  },
  {
    name: 'Mutton Biryani',
    calories: 540, protein: 28, carbs: 65, fat: 18, fiber: 2,
    price: 250, servingSize: '1 plate (370g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'rice', mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Rich mutton biryani — wedding and Eid staple in Pakistan',
  },
  {
    name: 'Matar Pulao',
    calories: 320, protein: 9, carbs: 58, fat: 7, fiber: 4,
    price: 80, servingSize: '1 plate (300g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'rice', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Fragrant peas and rice pilaf',
  },
  {
    name: 'Brown Rice (Unpolished)',
    calories: 215, protein: 5, carbs: 45, fat: 2, fiber: 3,
    price: 40, servingSize: '1 cup cooked (180g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'rice', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Whole grain brown rice — lower glycemic, more fiber than white rice',
  },
  {
    name: 'Yakhni Pulao',
    calories: 360, protein: 20, carbs: 55, fat: 8, fiber: 2,
    price: 160, servingSize: '1 plate (320g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: true,
    category: 'rice', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Bone broth rice — aromatic rice cooked in meat stock, Northern Pakistan favorite',
  },

  // ══════════════════════════════════════════════════════
  // DAIRY
  // ══════════════════════════════════════════════════════
  {
    name: 'Dahi (Plain Yogurt)',
    calories: 120, protein: 9, carbs: 10, fat: 4, fiber: 0,
    price: 40, servingSize: '1 cup (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dairy', mealType: ['breakfast', 'lunch', 'dinner', 'snack'],
    allergens: ['dairy'],
    description: 'Plain Pakistani yogurt — probiotic rich, low fat',
  },
  {
    name: 'Raita',
    calories: 100, protein: 5, carbs: 10, fat: 4, fiber: 1,
    price: 30, servingSize: '1 cup (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dairy', mealType: ['lunch', 'dinner'],
    allergens: ['dairy'],
    description: 'Yogurt with cucumber and mint',
  },
  {
    name: 'Low-Fat Milk (1 glass)',
    calories: 100, protein: 8, carbs: 12, fat: 2, fiber: 0,
    price: 30, servingSize: '1 glass (250ml)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dairy', mealType: ['breakfast', 'snack'],
    allergens: ['dairy'],
    description: 'Low-fat dairy milk — good protein source with reduced saturated fat',
  },
  {
    name: 'Paneer (Cottage Cheese)',
    calories: 260, protein: 18, carbs: 4, fat: 20, fiber: 0,
    price: 100, servingSize: '100g',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dairy', mealType: ['lunch', 'dinner', 'snack'],
    allergens: ['dairy'],
    description: 'Fresh Pakistani cottage cheese — protein-rich, used in many dishes',
  },

  // ══════════════════════════════════════════════════════
  // SNACKS
  // ══════════════════════════════════════════════════════
  {
    name: 'Fruit Chaat',
    calories: 130, protein: 2, carbs: 30, fat: 1, fiber: 4,
    price: 60, servingSize: '1 bowl (200g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'snack', mealType: ['snack'],
    allergens: [],
    description: 'Mixed seasonal fruits with chaat masala — Pakistani street snack',
  },
  {
    name: 'Roasted Chana',
    calories: 170, protein: 10, carbs: 25, fat: 3, fiber: 7,
    price: 25, servingSize: '1 handful (50g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'snack', mealType: ['snack'],
    allergens: [],
    description: 'Dry roasted chickpeas — healthy high-protein snack, widely available',
  },
  {
    name: 'Cucumber Salad (Kheera)',
    calories: 30, protein: 1, carbs: 6, fat: 0.5, fiber: 2,
    price: 20, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'snack', mealType: ['snack', 'lunch', 'dinner'],
    allergens: [],
    description: 'Fresh cucumber salad — zero-guilt snack, safe for all conditions',
  },
  {
    name: 'Green Tea',
    calories: 5, protein: 0, carbs: 1, fat: 0, fiber: 0,
    price: 15, servingSize: '1 cup (240ml)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'beverage', mealType: ['breakfast', 'snack'],
    allergens: [],
    description: 'Green tea — antioxidant rich, zero calories, safe for all conditions',
  },
  {
    name: 'Pakora (Besan)',
    calories: 200, protein: 6, carbs: 24, fat: 9, fiber: 2,
    price: 40, servingSize: '4 pieces (100g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'snack', mealType: ['snack'],
    allergens: ['gluten'],
    description: 'Chickpea flour fritters with vegetables — Ramadan and monsoon snack',
  },
  {
    name: 'Gol Gappa (Pani Puri)',
    calories: 150, protein: 3, carbs: 28, fat: 4, fiber: 2,
    price: 30, servingSize: '6 pieces (80g)',
    is_diabetic_safe: false, is_hypertension_safe: false, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'snack', mealType: ['snack'],
    allergens: ['gluten'],
    description: 'Crispy hollow shells with spiced water — popular street food across Pakistan',
  },
  {
    name: 'Chana Chaat',
    calories: 200, protein: 10, carbs: 30, fat: 5, fiber: 7,
    price: 50, servingSize: '1 bowl (200g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'snack', mealType: ['snack'],
    allergens: [],
    description: 'Spiced chickpea salad with tamarind chutney — healthy street food',
  },
  {
    name: 'Mixed Nuts (Small Portion)',
    calories: 160, protein: 5, carbs: 8, fat: 14, fiber: 2,
    price: 80, servingSize: '30g mixed almonds and walnuts',
    is_diabetic_safe: true, is_hypertension_safe: false, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'snack', mealType: ['snack'],
    allergens: ['nuts'],
    description: 'Heart-healthy fats — caution for hypertension; avoid in kidney disease',
  },

  // ══════════════════════════════════════════════════════
  // FRUITS (LOCAL PAKISTAN)
  // ══════════════════════════════════════════════════════
  {
    name: 'Apple (1 medium)',
    calories: 80, protein: 0.5, carbs: 21, fat: 0.3, fiber: 4,
    price: 35, servingSize: '1 medium apple (180g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'fruit', mealType: ['snack', 'breakfast'],
    allergens: [],
    description: 'Fresh apple — low glycemic, kidney-safe, widely available year-round',
  },
  {
    name: 'Guava (Amrood)',
    calories: 70, protein: 2, carbs: 15, fat: 0.5, fiber: 5,
    price: 25, servingSize: '1 medium guava (150g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'fruit', mealType: ['snack'],
    allergens: [],
    description: 'Pakistani guava — very high fiber, Vitamin C, low potassium, excellent for all conditions. Season: Aug-Feb',
  },
  {
    name: 'Banana',
    calories: 90, protein: 1, carbs: 23, fat: 0.3, fiber: 2.5,
    price: 20, servingSize: '1 medium banana (120g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'fruit', mealType: ['breakfast', 'snack'],
    allergens: [],
    description: 'Banana — widely available, good energy. High potassium: limit in kidney disease',
  },
  {
    name: 'Papaya (Papita)',
    calories: 55, protein: 1, carbs: 14, fat: 0.2, fiber: 2,
    price: 30, servingSize: '1 cup sliced (150g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'fruit', mealType: ['breakfast', 'snack'],
    allergens: [],
    description: 'Papaya — digestive enzyme papain, excellent for constipation and heart. Available year-round',
  },
  {
    name: 'Mango (Aam)',
    calories: 100, protein: 1, carbs: 25, fat: 0.4, fiber: 2,
    price: 60, servingSize: '1 medium mango (200g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'fruit', mealType: ['snack', 'breakfast'],
    allergens: [],
    description: 'Pakistani mango — national fruit, Anwar Ratol and Sindhri varieties. Season: May-August',
  },
  {
    name: 'Kinnow (Citrus)',
    calories: 65, protein: 1, carbs: 16, fat: 0.2, fiber: 2,
    price: 25, servingSize: '1 kinnow (150g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'fruit', mealType: ['snack', 'breakfast'],
    allergens: [],
    description: 'Pakistani citrus — high Vitamin C, aids iron absorption for anemia. Season: Nov-March',
  },
  {
    name: 'Watermelon (Tarbooz)',
    calories: 45, protein: 1, carbs: 11, fat: 0.2, fiber: 1,
    price: 20, servingSize: '1 slice (200g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'fruit', mealType: ['snack'],
    allergens: [],
    description: 'Watermelon — summer cooling fruit, very popular in Pakistan. Season: May-Aug',
  },
  {
    name: 'Pomegranate (Anar)',
    calories: 80, protein: 1.5, carbs: 19, fat: 0.5, fiber: 4,
    price: 80, servingSize: '1 cup arils (150g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'fruit', mealType: ['snack'],
    allergens: [],
    description: 'Pomegranate — antioxidant-rich, iron-boosting, heart-healthy. Season: Oct-Jan',
  },
  {
    name: 'Dates (Khajoor)',
    calories: 280, protein: 2, carbs: 75, fat: 0.5, fiber: 7,
    price: 100, servingSize: '6-7 dates (60g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'fruit', mealType: ['snack', 'breakfast'],
    allergens: [],
    description: 'Pakistani dates — iron-rich, high fiber, excellent for anemia and constipation. Available year-round dried',
  },
  {
    name: 'Grapes (Angoor)',
    calories: 70, protein: 0.7, carbs: 18, fat: 0.2, fiber: 1,
    price: 60, servingSize: '1 cup (150g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'fruit', mealType: ['snack'],
    allergens: [],
    description: 'Grapes — antioxidant resveratrol, heart-healthy. Season: Aug-Oct. Balochistan variety famous',
  },
  {
    name: 'Pear (Naashpati)',
    calories: 60, protein: 0.5, carbs: 15, fat: 0.1, fiber: 3,
    price: 40, servingSize: '1 medium pear (150g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'fruit', mealType: ['snack'],
    allergens: [],
    description: 'Pear — low glycemic, good fiber, kidney-safe, widely available in Pakistan',
  },
  {
    name: 'Strawberry (Strawberry)',
    calories: 45, protein: 1, carbs: 11, fat: 0.2, fiber: 2,
    price: 80, servingSize: '1 cup (150g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: true,
    category: 'fruit', mealType: ['snack', 'breakfast'],
    allergens: [],
    description: 'Strawberry — Vitamin C rich, enhances iron absorption. Season: Jan-Mar in Punjab',
  },

  // ══════════════════════════════════════════════════════
  // KIDNEY-SPECIFIC SAFE MEALS
  // ══════════════════════════════════════════════════════
  {
    name: 'Rice Porridge with Egg White',
    calories: 200, protein: 15, carbs: 30, fat: 2, fiber: 1,
    price: 50, servingSize: '1 bowl (300g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'breakfast', mealType: ['breakfast'],
    allergens: ['eggs'],
    description: 'Soft rice congee with egg whites — ideal for kidney patients, controlled protein',
  },
  {
    name: 'Lauki Dal (Low Protein)',
    calories: 150, protein: 6, carbs: 25, fat: 3, fiber: 4,
    price: 50, servingSize: '1 bowl (250g)',
    is_diabetic_safe: true, is_hypertension_safe: true, is_cardiac_safe: true,
    is_kidney_safe: true, is_thyroid_safe: true, is_constipation_safe: true, is_anemia_safe: false,
    category: 'lentils', mealType: ['lunch', 'dinner'],
    allergens: [],
    description: 'Bottle gourd with minimal lentils — specially designed for CKD patients',
  },

  // ══════════════════════════════════════════════════════
  // DESSERTS
  // ══════════════════════════════════════════════════════
  {
    name: 'Kheer (Rice Pudding)',
    calories: 280, protein: 7, carbs: 48, fat: 7, fiber: 0.5,
    price: 70, servingSize: '1 bowl (200g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dessert', mealType: ['dinner', 'snack'],
    allergens: ['dairy'],
    description: 'Pakistani rice pudding with milk and cardamom — Eid and wedding dessert',
  },
  {
    name: 'Sewaiyan (Vermicelli Pudding)',
    calories: 300, protein: 6, carbs: 52, fat: 8, fiber: 1,
    price: 60, servingSize: '1 bowl (200g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dessert', mealType: ['breakfast', 'snack'],
    allergens: ['gluten', 'dairy'],
    description: 'Vermicelli milk pudding — Eid morning tradition in Pakistan',
  },
  {
    name: 'Zarda (Sweet Rice)',
    calories: 350, protein: 5, carbs: 70, fat: 7, fiber: 1,
    price: 80, servingSize: '1 plate (250g)',
    is_diabetic_safe: false, is_hypertension_safe: true, is_cardiac_safe: false,
    is_kidney_safe: false, is_thyroid_safe: true, is_constipation_safe: false, is_anemia_safe: false,
    category: 'dessert', mealType: ['snack', 'dinner'],
    allergens: ['nuts', 'dairy'],
    description: 'Sweet saffron rice with nuts and raisins — Pakistani celebration dessert',
  },
];

const seedFoods = async () => {
  try {
    await connectDB();

    const existingCount = await FoodItem.countDocuments();
    if (existingCount > 0) {
      console.log(`\n⚠️  Database already has ${existingCount} food items.`);
      console.log('   Clearing and reseeding with extended authentic catalogue...\n');
      await FoodItem.deleteMany({});
    }

    const inserted = await FoodItem.insertMany(pakistaniFoods);
    console.log(`\n✅ Successfully seeded ${inserted.length} authentic Pakistani food items!\n`);

    // Summary
    const categories = [...new Set(pakistaniFoods.map((f) => f.category))];
    console.log('📦 Categories seeded:', categories.join(', '));
    console.log('🩸 Diabetic-safe items:', pakistaniFoods.filter((f) => f.is_diabetic_safe).length);
    console.log('❤️  Cardiac-safe items:', pakistaniFoods.filter((f) => f.is_cardiac_safe).length);
    console.log('💉 Hypertension-safe items:', pakistaniFoods.filter((f) => f.is_hypertension_safe).length);
    console.log('🫘 Kidney-safe items:', pakistaniFoods.filter((f) => f.is_kidney_safe).length);
    console.log('🦋 Thyroid-safe items:', pakistaniFoods.filter((f) => f.is_thyroid_safe).length);
    console.log('🌿 Constipation-safe items:', pakistaniFoods.filter((f) => f.is_constipation_safe).length);
    console.log('🩺 Anemia-safe items:', pakistaniFoods.filter((f) => f.is_anemia_safe).length);

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seedFoods();
